### ISSUE TITLE
add manual editing of points in step 2.clean

### ISSUE THREAD

**Issue by stevenpbachman** [stevenpbachman/rapidLC_top#36]
Users want to be able to click or select (marquee?) points and delete them. Possibly something similar in Wallace? https://github.com/wallaceEcoMod/wallace 
Alos, this may be useful: https://www.r-spatial.org/r/2017/01/30/mapedit_intro.html
Or here: https://stackoverflow.com/questions/34348737/r-leaflet-how-to-click-on-map-and-add-a-circle

**Comment by barnabywalker** [comment]
Same issue as #65
