### ISSUE TITLE
Maximum upload size exceeded

### ISSUE THREAD

**Issue by Xuletajr** [stevenpbachman/rapidLC_top#92]
Dear Steven,

I am using the rapid Rapid Least Concern to compare with Brazilian endemic tree assessment reviewed by CNCFlora (IUCN Brazilian plant Red List Authority Group). When I tried upload a csv file with species names and coordinates the app returned the following message "Maximum upload size exceeded". Our csv file has 798 species and 37,915 occurrences. What is the maximum upload size (number of occurrences)?

Thank you for your attention and cooperation. 

I look forward to hearing from you.

**Comment by stevenpbachman** [comment]
Hi @Xuletajr - thanks for the message and sorry for slow reply. I didn't know about the max upload limit, which I think is a shiny default of 5 mb per file https://groups.google.com/forum/#!msg/shiny-discuss/rU3vwGMZexQ/zeKhiYXrtEQJ 
It looks like we could change the default, but to be honest, we already see some performance issues when getting above more than 100 species. So, for now I'm afraid you'll have to split your datasets up into smaller chunks and run them separately. 
We are planning to write this up as a package, which should give us a few more options in terms of batch processing. Let me know how you get on.

**Comment by Xuletajr** [comment]
Hi Steven,

thank you very much for your attention and help. 

First, I split my database, but still had an error message to small spreadsheet. I looked for possible errors in this spreadsheet and saw that one species had coordinates in degrees and minutes. So, I changed these coordinates to decimal degrees, and now I'm not having issues with the maximum upload size. 

Best regards,
